name: 2-FOX
favicon: null
layout_spectrum: 0.825096549699083
typography_spectrum: 0.050211488269269466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#a82500'
    - '#6f7084'
    - '#ffffff'
    - '#ffaf9e'
  brandStrength: 0.9375
  lightness: 0.6082216564100236
  saturation: 0.07505659502930939
  rhythmicContrast: 0.4253004842903465
purpose: []
