name: 2-FOX
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#a82500'
    - '#6f7084'
    - '#ffffff'
    - '#ffaf9e'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
